# Sensors/Model covariances
localization/dvl_covariance: [0.002, 0.002, 0.002] # computed wrt bottom
localization/gps_covariance: [5.0, 5.0]
localization/model_covariance: [0.02, 0.02, 0.02]

#If DVL velocity is bigger than "merged_navigation/dvl_max_v" in m/s it puts it to 0.0
localization/dvl_max_v: 1.0
localization/gps_update: True
localization/gps_init_samples: 6

localization/check_sensors_period: 2.0
localization/dvl_max_period_error: 0.5
localization/svs_max_period_error: 1.0
localization/imu_max_period_error: 0.5
localization/max_init_time: 10.0
