joy/min_x_v: -0.3
joy/max_x_v: 0.3
joy/x_inc: 0.05
joy/min_y_v: -0.15
joy/max_y_v: 0.15
joy/y_inc: 0.03
joy/min_z_v: -0.20
joy/max_z_v: 0.20
joy/z_inc: 0.05
joy/min_yaw_v: -1.0
joy/max_yaw_v: 1.0
joy/yaw_inc: 0.2

joint/min_arm_v: -2.20
joint/max_arm_v: 1.60
joint/arm_inc : 0.05
joint/min_hand_v : -1.90
joint/max_hand_v : 1.90
joint/hand_inc : 0.05
joint/min_support_v : -3.14
joint/max_support_v : 3.14
joint/support_inc : 0.05
